export const REGISTER_VISITOR = "REGISTER_VISITOR";
export const LOGIN_VISITOR = "LOGIN_VISITOR";
export const LOGOUT_VISITOR = "LOGOUT_VISITOR";
export const LOAD_VISITOR = "LOAD_VISITOR";
export const FAIL_VISITOR = "FAIL_VISITOR";
export const CURRENT_VISITOR = "CURRENT_VISITOR";
export const CLEAR_ERRORS_VISITOR = "CLEAR_ERRORS_VISITOR";
